name = "Gustavo"
uuid = "b6f820fd-87a9-4cf8-8bd4-0e8dc9bb4263"
authors = ["Paul Tiede <ptiede91@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
